spring:
  application.name: app-user
  main.banner-mode: off

logging:
  level:
    root: info
    org.springframework.web: info
    kz.tottory.app.user: debug
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr([%thread]){cyan} %highlight(%-5level ) %clr([%X{traceId}]){magenta} %clr(%-40.40logger){purple} : %highlight(%msg%n )"